runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:
- url: /(index.html){0,1}
  static_files: index.html
  upload: index.html
  secure: always

- url: /css
  static_dir: css
  secure: always

- url: /js
  static_dir: js
  secure: always

- url: /(event|events)(/.*){0,1}
  script: server.app
  secure: always

- url: /(register|login|logout|getuser|oidcauth)
  script: login.app
  secure: always

- url: /migrate
  script: migrate.app
  secure: always

- url: /init
  script: secret.app
  secure: always